const outfits = [
  {
    id: 1,
    title: "Casual Summer Outfit",
    category: "Casual",
    season: "Dry",
    description: "Light t-shirt and shorts perfect for summer.",
    image: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=800",
    price: 12000,
    keywords: ["casual", "dry", "light"],
  },
  {
    id: 2,
    title: "Rainy Day Essentials",
    category: "Casual",
    season: "Rainy",
    description: "Waterproof jacket and jeans for staying dry.",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800",
    price: 25000,
    keywords: ["casual", "rainy", "waterproof"],
  },
  {
    id: 3,
    title: "Business Professional",
    category: "Formal",
    season: "Dry",
    description: "Sharp suit and tie for the office.",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800",
    price: 45000,
    keywords: ["formal", "dry", "business"],
  },
  {
    id: 4,
    title: "Active Sportswear",
    category: "Athletic",
    season: "Dry",
    description: "Breathable athletic wear for workouts.",
    image: "https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=800",
    price: 18000,
    keywords: ["athletic", "dry", "workout"],
  },
  {
    id: 5,
    title: "Cozy Rainy Evening",
    category: "Casual",
    season: "Rainy",
    description: "Warm sweater and comfortable pants.",
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800",
    price: 22000,
    keywords: ["casual", "rainy", "cozy"],
  },
  {
    id: 6,
    title: "Beach Day Vibes",
    category: "Casual",
    season: "Dry",
    description: "Tank top and beach shorts for sunny days.",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
    price: 15000,
    keywords: ["casual", "dry", "beach"],
  },
  {
    id: 7,
    title: "Evening Gala",
    category: "Formal",
    season: "Dry",
    description: "Elegant dress for special occasions.",
    image: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800",
    price: 55000,
    keywords: ["formal", "dry", "elegant"],
  },
  {
    id: 8,
    title: "Monsoon Chic",
    category: "Casual",
    season: "Rainy",
    description: "Stylish raincoat with ankle boots.",
    image: "https://images.unsplash.com/photo-1604695573706-53170668f6a6?w=800",
    price: 28000,
    keywords: ["casual", "rainy", "stylish"],
  },
  {
    id: 9,
    title: "Running Gear",
    category: "Athletic",
    season: "Dry",
    description: "Moisture-wicking running outfit.",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800",
    price: 20000,
    keywords: ["athletic", "dry", "running"],
  },
  {
    id: 10,
    title: "Smart Casual Friday",
    category: "Smart Casual",
    season: "Dry",
    description: "Blazer with chinos for casual workplace.",
    image: "https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?w=800",
    price: 32000,
    keywords: ["smart casual", "dry", "workplace"],
  },
  {
    id: 11,
    title: "Rainy Commute",
    category: "Smart Casual",
    season: "Rainy",
    description: "Trench coat and water-resistant shoes.",
    image: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800",
    price: 38000,
    keywords: ["smart casual", "rainy", "commute"],
  },
  {
    id: 12,
    title: "Tropical Vacation",
    category: "Casual",
    season: "Dry",
    description: "Linen shirt and light pants for travel.",
    image: "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?w=800",
    price: 24000,
    keywords: ["casual", "dry", "vacation"],
  },
  {
    id: 13,
    title: "Yoga Session",
    category: "Athletic",
    season: "Dry",
    description: "Flexible leggings and sports bra.",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800",
    price: 16000,
    keywords: ["athletic", "dry", "yoga"],
  },
  {
    id: 14,
    title: "Winter Rainy Day",
    category: "Casual",
    season: "Rainy",
    description: "Hooded parka and warm layers.",
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800",
    price: 35000,
    keywords: ["casual", "rainy", "warm"],
  },
  {
    id: 15,
    title: "Classic Wedding Guest",
    category: "Formal",
    season: "Dry",
    description: "Sophisticated cocktail dress or suit.",
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800",
    price: 48000,
    keywords: ["formal", "dry", "wedding"],
  },
  {
    id: 16,
    title: "Outdoor Adventure",
    category: "Athletic",
    season: "Rainy",
    description: "Waterproof hiking gear with boots.",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800",
    price: 42000,
    keywords: ["athletic", "rainy", "hiking"],
  },
  {
    id: 17,
    title: "Brunch Date",
    category: "Smart Casual",
    season: "Dry",
    description: "Sundress or polo with slacks.",
    image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800",
    price: 26000,
    keywords: ["smart casual", "dry", "brunch"],
  },
  {
    id: 18,
    title: "Stormy Office Day",
    category: "Formal",
    season: "Rainy",
    description: "Water-resistant business suit.",
    image: "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800",
    price: 52000,
    keywords: ["formal", "rainy", "business"],
  },
  {
    id: 19,
    title: "Festival Ready",
    category: "Casual",
    season: "Dry",
    description: "Boho chic outfit with accessories.",
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800",
    price: 19000,
    keywords: ["casual", "dry", "festival"],
  },
  {
    id: 20,
    title: "Gym Training",
    category: "Athletic",
    season: "Dry",
    description: "Performance shorts and tank top.",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800",
    price: 17000,
    keywords: ["athletic", "dry", "gym"],
  },
];
 export default outfits